// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: creator_balance.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getCreatorBalance = `-- name: GetCreatorBalance :one
select creator_id, lamports from creator_balance
	where creator_id=$1
`

func (q *Queries) GetCreatorBalance(ctx context.Context, creatorID uuid.UUID) (CreatorBalance, error) {
	row := q.db.QueryRowContext(ctx, getCreatorBalance, creatorID)
	var i CreatorBalance
	err := row.Scan(&i.CreatorID, &i.Lamports)
	return i, err
}
